//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Web.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketManagementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketManagementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagement.Web.Resources.TicketManagementResource", typeof(TicketManagementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в корзину.
        /// </summary>
        public static string AddInBasket {
            get {
                return ResourceManager.GetString("AddInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область не найдена.
        /// </summary>
        public static string AreaNotFound {
            get {
                return ResourceManager.GetString("AreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Области.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В областях нет мест.
        /// </summary>
        public static string AreasNotHasSeats {
            get {
                return ResourceManager.GetString("AreasNotHasSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к списку.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться в профиль.
        /// </summary>
        public static string BackToProfile {
            get {
                return ResourceManager.GetString("BackToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пуста.
        /// </summary>
        public static string BasketEmptyException {
            get {
                return ResourceManager.GetString("BasketEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала.
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала не может быть больше даты окончания.
        /// </summary>
        public static string BeginDateLongerEndDateException {
            get {
                return ResourceManager.GetString("BeginDateLongerEndDateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        public static string BeginTime {
            get {
                return ResourceManager.GetString("BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить корзину.
        /// </summary>
        public static string ClearBasket {
            get {
                return ResourceManager.GetString("ClearBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество свободных мест.
        /// </summary>
        public static string CountFreeSeats {
            get {
                return ResourceManager.GetString("CountFreeSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие не может быть создано в одно и то же время с другим событием в одном месте.
        /// </summary>
        public static string CreateEventInLayoutInTheSameTimeException {
            get {
                return ResourceManager.GetString("CreateEventInLayoutInTheSameTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать событие в прошлом.
        /// </summary>
        public static string CreateInPastException {
            get {
                return ResourceManager.GetString("CreateInPastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить эту запись?.
        /// </summary>
        public static string DeletingConfirm {
            get {
                return ResourceManager.GetString("DeletingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string EditPass {
            get {
                return ResourceManager.GetString("EditPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить профиль.
        /// </summary>
        public static string EditUserProfile {
            get {
                return ResourceManager.GetString("EditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Электронная почта&quot; должно быть заполнено.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пуста..
        /// </summary>
        public static string EmptyCart {
            get {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список событий пуст..
        /// </summary>
        public static string EmptyEventList {
            get {
                return ResourceManager.GetString("EmptyEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не было совершено покупок на этом аккаунте..
        /// </summary>
        public static string EmptyPurchaseHistory {
            get {
                return ResourceManager.GetString("EmptyPurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие уже опубликовано.
        /// </summary>
        public static string EventAlreadyPublishedException {
            get {
                return ResourceManager.GetString("EventAlreadyPublishedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область события не найдена.
        /// </summary>
        public static string EventAreaNotFound {
            get {
                return ResourceManager.GetString("EventAreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о событии.
        /// </summary>
        public static string EventInfo {
            get {
                return ResourceManager.GetString("EventInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие не может быть создано в прошлом.
        /// </summary>
        public static string EventInPastException {
            get {
                return ResourceManager.GetString("EventInPastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя отменить публикацию, один или более билетов уже продано.
        /// </summary>
        public static string EventIsNotCancelException {
            get {
                return ResourceManager.GetString("EventIsNotCancelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие нельзя удалить (редактировать), поскольку один или несколько билетов были проданы.
        /// </summary>
        public static string EventIsNotDeletingException {
            get {
                return ResourceManager.GetString("EventIsNotDeletingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие не может быть создано без мест.
        /// </summary>
        public static string EventNotCreatedWitoutSeatsException {
            get {
                return ResourceManager.GetString("EventNotCreatedWitoutSeatsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие не найдено.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие уже прошло.
        /// </summary>
        public static string EventPassedException {
            get {
                return ResourceManager.GetString("EventPassedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место события не найдено.
        /// </summary>
        public static string EventSeatNotFound {
            get {
                return ResourceManager.GetString("EventSeatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже существует область с этим описанием.
        /// </summary>
        public static string ExistAreaWithDescription {
            get {
                return ResourceManager.GetString("ExistAreaWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Имя&quot; должно быть заполнено.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение не найдено.
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная сумма.
        /// </summary>
        public static string IncorrectCurrency {
            get {
                return ResourceManager.GetString("IncorrectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный адрес электронной почты.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        public static string IncreaseBalance {
            get {
                return ResourceManager.GetString("IncreaseBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение не имеет мест.
        /// </summary>
        public static string LayoutHasNotSeatException {
            get {
                return ResourceManager.GetString("LayoutHasNotSeatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string LayoutId {
            get {
                return ResourceManager.GetString("LayoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение не найдено.
        /// </summary>
        public static string LayoutNotFound {
            get {
                return ResourceManager.GetString("LayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение не имеет областей.
        /// </summary>
        public static string LayoutNotHasAreasException {
            get {
                return ResourceManager.GetString("LayoutNotHasAreasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите учетные данные.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События (менеджер).
        /// </summary>
        public static string ManagerEvents {
            get {
                return ResourceManager.GetString("ManagerEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Имя&quot; должно быть заполнено.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно денег на счете.
        /// </summary>
        public static string NotEnoughMoneyException {
            get {
                return ResourceManager.GetString("NotEnoughMoneyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет выбранных мест.
        /// </summary>
        public static string NotSelectedSeatsException {
            get {
                return ResourceManager.GetString("NotSelectedSeatsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть от 8 до 20 символов.
        /// </summary>
        public static string PasswordMustBeFrom8To20symb {
            get {
                return ResourceManager.GetString("PasswordMustBeFrom8To20symb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Пароль&quot; должно быть заполнено.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это платформа, которая позволяет покупать билеты на различные мероприятия в вашей стране..
        /// </summary>
        public static string PlatformDescription {
            get {
                return ResourceManager.GetString("PlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформа управления билетами.
        /// </summary>
        public static string PlatformName {
            get {
                return ResourceManager.GetString("PlatformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        public static string ProfileGeneral {
            get {
                return ResourceManager.GetString("ProfileGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовать.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата покупки.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История покупок.
        /// </summary>
        public static string PurchaseHistory {
            get {
                return ResourceManager.GetString("PurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string PurchaseName {
            get {
                return ResourceManager.GetString("PurchaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить счет.
        /// </summary>
        public static string PutMoney {
            get {
                return ResourceManager.GetString("PutMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место на данный момент занято.
        /// </summary>
        public static string SeatIsNotFree {
            get {
                return ResourceManager.GetString("SeatIsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место не найдено.
        /// </summary>
        public static string SeatNotFound {
            get {
                return ResourceManager.GetString("SeatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить стоимость областей.
        /// </summary>
        public static string SetAreasCosts {
            get {
                return ResourceManager.GetString("SetAreasCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все области в событии должны иметь цену.
        /// </summary>
        public static string SetCostsEventException {
            get {
                return ResourceManager.GetString("SetCostsEventException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина строки должна быть от 2 до 30 символов.
        /// </summary>
        public static string StringLenghtMessageFrom2to30symb {
            get {
                return ResourceManager.GetString("StringLenghtMessageFrom2to30symb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина строки должна быть от 3 до 30 символов.
        /// </summary>
        public static string StringLenghtMessageFrom3to30symb {
            get {
                return ResourceManager.GetString("StringLenghtMessageFrom3to30symb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина строки должна быть от 5 символов.
        /// </summary>
        public static string StringLenghtMessageFrom5symb {
            get {
                return ResourceManager.GetString("StringLenghtMessageFrom5symb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Фамилия&quot; должно быть заполнено.
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовой пояс.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить.
        /// </summary>
        public static string TopUp {
            get {
                return ResourceManager.GetString("TopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прерванное исключение транзакции.
        /// </summary>
        public static string TransactionAbortedException {
            get {
                return ResourceManager.GetString("TransactionAbortedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ряд и номер места должны быть уникальными для области.
        /// </summary>
        public static string UniqueRowAndNumber {
            get {
                return ResourceManager.GetString("UniqueRowAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        public static string UnknownUserError {
            get {
                return ResourceManager.GetString("UnknownUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка. Мы работаем над этим. Пожалуйста, попробуйте еще раз через некоторое время..
        /// </summary>
        public static string UnknownUserErrorDescription {
            get {
                return ResourceManager.GetString("UnknownUserErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не опубликовывать.
        /// </summary>
        public static string UnPublished {
            get {
                return ResourceManager.GetString("UnPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с этим именем или электронной почтой уже существует.
        /// </summary>
        public static string UserExistException {
            get {
                return ResourceManager.GetString("UserExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о пользователе.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Имя пользователя&quot; должно быть заполнено.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или пароль не верны.
        /// </summary>
        public static string UserOrPassword {
            get {
                return ResourceManager.GetString("UserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место не найдено.
        /// </summary>
        public static string VenueNotFound {
            get {
                return ResourceManager.GetString("VenueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть место с таким именем.
        /// </summary>
        public static string VenueWithThatNameException {
            get {
                return ResourceManager.GetString("VenueWithThatNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные данные.
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
